version: '3.5'
services:
    mongo:
          image: mongo
          container_name: mongo
          restart: always
          environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
          ports:
            - 27017:27017
          volumes:
            - mongodata:/data/db
          networks:
            - common-network
    order-service:
          image: order-service
          container_name: order-service
          ports:
            - 8080:8080
            - 6566:6566
            - 5555:5555
          depends_on:
            - mongo
          networks:
            - common-network
    product:
          image: product-service
          container_name: product-service
          ports:
            - 8081:8081
            - 6567:6567
          depends_on:
            - order-service
          networks:
            - common-network
    notification:
          image: notification-service
          container_name: notification-service
          depends_on:
            - order-service
          networks:
            - common-network
    app-store:
          image: app-store
          container_name: app-store
          ports:
            - 3000:3000
          depends_on:
            - mongo
            - order-service
            - product
          networks:
            - common-network
            
volumes:
  mongodata:
networks:
  common-network:
    name: kafka_broker-kafka
    external: true
